### ISSUE TITLE
NotFoundError: Key RNN/basic_lstm_cell/bias not found

### ISSUE THREAD

**Issue by raghavgurbaxani** [mlberkeley/oreilly-captions#17]
NotFoundError: Key RNN/basic_lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

hi, could you help out with this issue please ?

**Comment by SpeedOfSpin** [comment]
Its because this was trained on TF 1.0 and you are probably on a later version
Insert a new cell in the first notebook and paste this in

`
OLD_CHECKPOINT_FILE = "./models/tf_final/model-500"
NEW_CHECKPOINT_FILE = "./models/tf_final2/model-500"

import tensorflow as tf
vars_to_rename = {
    "RNN/basic_lstm_cell/weights": "RNN/basic_lstm_cell/kernel",
    "RNN/basic_lstm_cell/biases": "RNN/basic_lstm_cell/bias",
}
new_checkpoint_vars = {}
reader = tf.train.NewCheckpointReader(OLD_CHECKPOINT_FILE)
for old_name in reader.get_variable_to_shape_map():
  if old_name in vars_to_rename:
    new_name = vars_to_rename[old_name]
  else:
    new_name = old_name
  new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))

init = tf.global_variables_initializer()
saver = tf.train.Saver(new_checkpoint_vars)

with tf.Session() as sess:
  sess.run(init)
  saver.save(sess, NEW_CHECKPOINT_FILE)
`

Then change the model_path_transfer to
model_path_transfer = './models/tf_final2'

that should do it
